# Numpy

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import solve

## Create numpy arrays

In [2]:
np.array([1, 2]).shape

(2,)

In [3]:
np.array([ [1, 2], [3, 4] ]).shape

(2, 2)

In [4]:
np.array([ [1, 2], [3, 4], [5, 6] ]).shape

(3, 2)

In [5]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.randint(0, 100, [1000, 50])

array([[74, 42, 69, ..., 15, 43, 52],
       [72, 72, 46, ..., 84, 64, 19],
       [46, 60, 55, ...,  4,  6, 95],
       ...,
       [82, 85, 78, ..., 42, 38, 42],
       [10, 61,  3, ...,  8, 10, 49],
       [54, 63, 82, ..., 18, 41, 11]])

## Numpy operations

In [10]:
array = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
array[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
array[0]

array([1, 2, 3])

In [13]:
array[2]

array([7, 8, 9])

In [14]:
array[:, 0]

array([1, 4, 7])

In [15]:
array[:, 2:]

array([[3],
       [6],
       [9]])

In [16]:
array[1, 1]

5

In [17]:
array[-1, -1]

9

In [18]:
array_2 = np.concatenate([array, np.array([ [10, 11, 12] ])])
array_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
array_2[0, 0] = 0
array_2

array([[ 0,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Matrix arithmetic and linear systems

In [20]:
array_1 = np.array([1, 2])
array_1

array([1, 2])

In [21]:
array_2 = np.array([3, 4])
array_2

array([3, 4])

In [22]:
array_1 + array_2

array([4, 6])

In [23]:
array_1 - array_2

array([-2, -2])

In [24]:
array_1 * 2

array([2, 4])

In [25]:
array_1 ** 3

array([1, 8])

In [26]:
array_1 * array_2

array([3, 8])

In [27]:
np.dot(array_1, array_2)

11

In [28]:
mat_1 = np.array([ [1, 2, 3], [4, 5, 6] ])
mat_1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
mat_1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
mat_2 = np.array([ [1, 2, 3], [4, 5, 6] ])
mat_2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
mat_1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [32]:
mat_1 * mat_2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
np.dot(mat_1, mat_2.T)

array([[14, 32],
       [32, 77]])

In [34]:
inv(np.eye(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
mat_3 = np.matrix([ [1, 2], [3, 4] ])
mat_3

matrix([[1, 2],
        [3, 4]])

In [36]:
inv(mat_3)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## Broadcasting

perform arithmetic operations on different shaped arrays

smaller array is broadcast across the larger array to ensure shape consistency

Rules:

* one dimension (either column or row) should have the same dimension for both arrays
* the lower dimension array should be a 1d array

In [37]:
mat_1 = np.arange(20).reshape(5, 4)
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
mat_2 = np.arange(5) # 1x5 cannot be added to mat_1
mat_3 = mat_2.reshape(5, 1)
mat_3

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [39]:
mat_1 + mat_3

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [40]:
mat_1 * mat_3

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22],
       [36, 39, 42, 45],
       [64, 68, 72, 76]])

## Solve equations

In [41]:
mat_1 = np.array([ [2, 1], [1, -1] ])
mat_1

array([[ 2,  1],
       [ 1, -1]])

In [42]:
array = np.array([4, -1])
array

array([ 4, -1])

In [43]:
solve(mat_1, array)

array([1., 2.])

In [44]:
inv_mat_1 = inv(mat_1)
inv_mat_1

array([[ 0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667]])

In [45]:
inv_mat_1.dot(array)

array([1., 2.])

In [46]:
mat_1 = np.array([ [1, 2, 3], [4, 5, 2], [2, 8, 5] ])
mat_1

array([[1, 2, 3],
       [4, 5, 2],
       [2, 8, 5]])

In [47]:
array = np.array([5, 10, 15])
array

array([ 5, 10, 15])

In [48]:
solve(mat_1, array)

array([0.46511628, 1.39534884, 0.58139535])

## Statistical operations

In [49]:
mat_1 = np.array([ [1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 6], [12, 7, 10, 9], [2, 11, 8, 10] ])
mat_1

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9,  6],
       [12,  7, 10,  9],
       [ 2, 11,  8, 10]])

In [50]:
mat_1.sum()

127

In [51]:
mat_1.sum(axis=0) # column wise sum

array([25, 32, 35, 35])

In [52]:
mat_1.sum(axis=1) # row wise sum

array([10, 18, 30, 38, 31])

In [53]:
mat_1.mean()

6.35

In [54]:
mat_1.mean(axis=0)

array([5. , 6.4, 7. , 7. ])

In [55]:
mat_1.mean(axis=1)

array([2.5 , 4.5 , 7.5 , 9.5 , 7.75])

In [56]:
np.median(mat_1)

6.5

In [57]:
np.median(mat_1, axis=0)

array([3., 7., 8., 6.])

In [58]:
np.std(mat_1, axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.80277564, 3.49106001])

In [59]:
np.std(mat_1)

3.182373328193912

In [60]:
# percentile: value below which a given percentage of observations can be found
percentile = [25, 50, 75]
for p in percentile:
    print(f'Percentile {p}: {np.percentile(mat_1, p, axis=1)}')

Percentile 25: [1.75 3.75 6.75 8.5  6.5 ]
Percentile 50: [2.5 4.5 7.5 9.5 9. ]
Percentile 75: [ 3.25  5.25  8.25 10.5  10.25]
