# Dimensionality reduction

In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import multiprocessing

random_state = 42
num_cpu = multiprocessing.cpu_count()
num_cpu

16

In [2]:
def read_data():
    df = pd.read_csv('data/fifa.csv')
    y = (df['Man of the Match'] == "Yes")
    feature_names = [i for i in df.columns if df[i].dtype in [np.int64]]
    X = df[feature_names]
    
    return train_test_split(X, y, random_state=random_state)

## Principal Component Analysis

Linear dimensionality reduction using Singular Valud Decomposition of the data to project it to a lower dimensional space.

* if the data is not linearly separable, use KernelPCA
* if the data is sparse: use TruncatedSVD

In [3]:
X_train, X_test, y_train, y_test = read_data()

In [4]:
X_train.head()

Goal Scored  Ball Possession %  Attempts  On-Target  Off-Target  Blocked  \
126            4                 39         8          6           1        1   
24             3                 61        15          6           7        2   
67             1                 39         8          1           6        1   
111            1                 51        16          2           9        5   
89             1                 46        11          2           5        4   

     Corners  Offsides  Free Kicks  Saves  Pass Accuracy %  Passes  \
126        2         1          14      1               75     271   
24         9         1          21      2               89     544   
67         2         3           8      5               82     357   
111        7         2          24      3               82     571   
89         7         0          12      3               83     462   

     Distance Covered (Kms)  Fouls Committed  Yellow Card  Yellow & Red  Red  \
126                      99               14            2             0    0   
24                      102               17            3             0    0   
67                      106               16            2             0    0   
111                     143               13            2             0    0   
89                       80                8            0             0    0   

     Goals in PSO  
126             0  
24              0  
67              0  
111             4  
89              0

In [5]:
X_train.describe()

Goal Scored  Ball Possession %   Attempts  On-Target  Off-Target  \
count    96.000000          96.000000  96.000000  96.000000   96.000000   
mean      1.302083          50.708333  12.354167   3.760417    5.156250   
std       1.134342           9.817189   5.131901   2.145962    2.522856   
min       0.000000          25.000000   3.000000   0.000000    1.000000   
25%       0.750000          43.000000   8.000000   2.000000    3.000000   
50%       1.000000          51.500000  12.000000   3.000000    5.000000   
75%       2.000000          58.000000  15.000000   5.000000    7.000000   
max       6.000000          75.000000  26.000000  12.000000   11.000000   

         Blocked    Corners   Offsides  Free Kicks      Saves  \
count  96.000000  96.000000  96.000000   96.000000  96.000000   
mean    3.375000   4.781250   1.333333   15.197917   2.541667   
std     2.367544   2.313362   1.092237    4.800482   1.907970   
min     0.000000   0.000000   0.000000    5.000000   0.000000   
25%     1.750000   3.000000   1.000000   11.000000   1.000000   
50%     3.000000   5.000000   1.000000   15.000000   2.000000   
75%     4.000000   6.000000   2.000000   18.000000   3.250000   
max    10.000000  11.000000   4.000000   26.000000   9.000000   

       Pass Accuracy %       Passes  Distance Covered (Kms)  Fouls Committed  \
count        96.000000    96.000000               96.000000        96.000000   
mean         82.750000   475.906250              106.781250        13.562500   
std           5.395905   150.822522               12.223535         4.414837   
min          67.000000   194.000000               80.000000         5.000000   
25%          79.000000   363.750000              101.000000        10.750000   
50%          83.000000   475.000000              104.000000        13.500000   
75%          87.000000   559.000000              108.000000        16.000000   
max          94.000000  1137.000000              148.000000        24.000000   

       Yellow Card  Yellow & Red        Red  Goals in PSO  
count    96.000000     96.000000  96.000000     96.000000  
mean      1.729167      0.010417   0.020833      0.239583  
std       1.260569      0.102062   0.143576      0.879531  
min       0.000000      0.000000   0.000000      0.000000  
25%       1.000000      0.000000   0.000000      0.000000  
50%       2.000000      0.000000   0.000000      0.000000  
75%       2.000000      0.000000   0.000000      0.000000  
max       6.000000      1.000000   1.000000      4.000000

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [7]:
pca = PCA(n_components=5, random_state=random_state)
principal_components = pca.fit_transform(X_train)

In [8]:
pca.explained_variance_ratio_

array([0.26592701, 0.12373013, 0.08229868, 0.08046827, 0.07463512])

These components shoulldn't be used because we lost too much information

In [9]:
df = pd.read_csv('data/iris.csv', index_col='Id')
df.head()

Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)  Petal Width (cm)  \
Id                                                                             
1                 5.1               3.5                1.4               0.2   
2                 4.9               3.0                1.4               0.2   
3                 4.7               3.2                1.3               0.2   
4                 4.6               3.1                1.5               0.2   
5                 5.0               3.6                1.4               0.2   

        Species  
Id               
1   Iris-setosa  
2   Iris-setosa  
3   Iris-setosa  
4   Iris-setosa  
5   Iris-setosa

In [10]:
features = ['Sepal Length (cm)', 'Sepal Width (cm)', 'Petal Length (cm)', 'Petal Width (cm)']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df[features], df["Species"])

In [12]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
pca = PCA(n_components=2)
principal_components = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
principal_df = pd.DataFrame(data=principal_components, columns=["PC1", "PC2"])
principal_df.head()

PC1       PC2
0  1.006900 -1.392834
1  2.728089  0.740575
2  1.998298  0.589342
3  1.129815 -0.693400
4  0.914315  0.021563

In [14]:
X_test[:5, :]

array([[ 0.22098316, -0.36652901],
       [-2.19184006, -0.65935506],
       [ 1.58127854,  0.66490586],
       [-2.53443298,  1.86207622],
       [ 0.24558718, -0.58112351]])

In [15]:
pca.explained_variance_ratio_

array([0.72618385, 0.23325304])

This is much more representative of the data, we didn't lose much information.

We can noow use this lowered dimension data for training a model.